### ISSUE TITLE
apply() operator

### ISSUE THREAD

**Issue by eshansingh** [staltz/xstream#100]
To make it easier to use the reducer pattern in Cycle.js apps, we could implement a `.apply()` operator, that takes a stream of functions and an initial value and does `stream.fold((value, function) => function(value), initialVal)`. You could define this very trivially on your own, but I feel that it would do better in the core.

Thoughts?

(P.S this is the 100th issue 🎉 )

**Comment by Hypnosphi** [comment]
I would choose another naming, `reduce` is too loaded. Something like `process(initValue)` or `apply(initValue)` would be better

**Comment by eshansingh** [comment]
You're right. `process()` is too generic, I think `apply()` will do.

**Comment by eshansingh** [comment]
One problem is `reducer$.apply(0)` would look pretty meaningless, with the supposedly magic "0" there. Is there a better way to do it?

**Comment by Hypnosphi** [comment]
read as "apply (a composition of) all those functions to zero"

**Comment by eshansingh** [comment]
Makes sense. Should I attempt a PR?

**Comment by staltz** [comment]
@eshansingh It's not worth making a PR for this because "you could define this very trivially on your own". Basically nothing gets added to core anymore, we ran out of space. Only critical fixes and similar refactorings. Extra is for adding functionality that cannot be already achieved with core operators. For instance delay and debounce cannot be accomplished with core operators. Neither can concat. So this "apply" wouldn't be an extra operator either. I think it's just a helper/util that you use in your own application. It's one line of code and then you can use it through .compose(apply(0))

**Comment by eshansingh** [comment]
Definitely agree with you, it was just a suggestion.

**Comment by Hypnosphi** [comment]
`delay(period)` is `stream.map(v => xs.periodic(period).take(1).mapTo(v)).compose(flattenConcurrently())`
`debounce(period)` is `stream.map(v => xs.periodic(period).take(1).mapTo(v)).flatten()`

**Comment by eshansingh** [comment]
@Hypnosphi Interesting. Those are pretty complex to write and understand though, so maybe @staltz has a point there. Because this is so simple to define on your own, maybe it's not worth putting it in core.
