### ISSUE TITLE
Typescript errors importing xstream .d.ts files from external app

### ISSUE THREAD

**Issue by antonycourtney** [staltz/xstream#117]
I'm attempting to use xstream as a library from a TypeScript application.

When I attempt to import xstream, I get the following errors:

```
ERROR in /private/tmp/tstoy/node_modules/xstream/extra/fromEvent.d.ts
(1,1): error TS2654: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.

ERROR in /private/tmp/tstoy/node_modules/xstream/core.d.ts
(97,8): error TS2304: Cannot find name 'Promise'.

ERROR in /private/tmp/tstoy/node_modules/xstream/core.d.ts
(98,20): error TS2304: Cannot find name 'Promise'.

ERROR in /private/tmp/tstoy/node_modules/xstream/core.d.ts
(426,36): error TS2304: Cannot find name 'Promise'.
```
Are there additional global TypeScript dependencies I need to have to use the typed interface to xstream?

I've committed my minimal test project to the followin public github repo: [](https://github.com/antonycourtney/tstoy)

To reproduce:
```
$ git clone https://github.com/antonycourtney/tstoy
$ cd tstoy
$ npm install
$ webpack
```

I'm new to TypeScript, so there is a fair chance that this issue is actually due to my own poor understanding of how typescript interacts with npm. Apologies in advance if that's the case; any help appreciated.

**Comment by antonycourtney** [comment]
Quick update:

I managed to work-around the triple slash reference by just deleting the errant line by hand in my local copy.

I managed to work around the other error messages by doing:
```
$ typings install --global --save-dev dt~es6-promise
$ typings install --global --save-dev dt~node
```
...which I guessed by looking at the `typings.json` file in the xstream repository. 
But are those really the right steps for using xstream from TypeScript?

**Comment by TylorS** [comment]
Hello @antonycourtney. XStream is written and assumed to have access to a Promise type. Instead of forcing a type onto you, which could lead to errors like `type Promise is not the same as type Promise` (no good), you'll need to provide your own Promise type. 

If you use TypeScript to compile to ES6 this will work for you automatically, but if you are compiling to ES5 you can use something like `es6-promise` installed. If you're using typings you can do `typings install dt~es6-promise` and if you are using TypeScript 2.x you can install the types from NPM I believe.
`npm install --save-dev @types/es6-promise` and in your tsconfig.json

```json
{
  "compilerOptions": {
    types: [ 'es6-promise' ]
  }
}
```

A third an final option I have, I believe also only works in TS 2.x you can include the ES2015 lib for typings like

```json
{
  "compilerOptions": {
    "lib": [
      "es2015"
    ]
  }
}
```

Hope this helps :)

**Comment by antonycourtney** [comment]
@TylorS Very helpful, thank you!

Since I found adequate workarounds for this and other issues, I'll go ahead and close this.
