### ISSUE TITLE
Publish on Bower?

### ISSUE THREAD

**Issue by brunjick** [staltz/xstream#129]
Would you mind publishing this library on Bower? Because NPM & bundling isn't always an option. Now I can use git link to fetch master but versioning would be great.
Thanks.

**Comment by staltz** [comment]
Hi. Thanks for submitting the issue, we appreciate feedback and suggestion improvements.
Sorry about this, there's no other way to say it: we won't do this issue. We used to have bower support, but in order to move faster (we are very small team overloaded with issues) we need to support less things, specially those that aren't so common.

Hope you understand. 🙇

**Comment by brunjick** [comment]
Sure I understand that, not a big issue though.
Thanks for your amazing work
