### ISSUE TITLE
typescript: combine doesn't work with MemoryStream

### ISSUE THREAD

**Issue by vitiral** [staltz/xstream#143]
I am running through the [cycle tutorial](https://cycle.js.org/model-view-intent.html) but am using typescript instead of javascript.

My `model` function looks like:
```
function model(actions: Actions): Stream<State> {
  const weight$ = actions.changeWeight$.startWith(70);
  const height$ = actions.changeWeight$.startWith(170);

  return xs.combine([weight$, height$])
    .map(([weight, height]) => new Stream(
      weight, height, calc_bmi(height, weight)))
}
```

However, I am getting the following compiler error:
```
ERROR in [default] /home/garrett/notes/typescript/cycle/bmi_calc/src/app.ts:63:20 
Argument of type 'MemoryStream<number>[]' is not assignable to parameter of type 'Stream<any>'.
  Property '_prod' is missing in type 'MemoryStream<number>[]'.
```

Looking at the source code in master, it looks like `combine` is only defined for `Stream` and not `MemoryStream`.

Here are all the errors I am geting from that section of code, I'm not sure why I'm getting the other ones either (the types should be inferred I would think:
```
typescript/cycle/bmi_calc/src/app.ts|64 col 21 error| Argument of type 'MemoryStream<number>[]' is not assignable to parameter of type 'Stream<any>'. Property '_prod' is missing in type                          #////#'MemoryStream<number>[]'.                                                     
typescript/cycle/bmi_calc/src/app.ts|65 col 12 error| Binding element 'weight' implicitly has an 'any' type.
typescript/cycle/bmi_calc/src/app.ts|65 col 20 error| Binding element 'height' implicitly has an 'any' type.
typescript/cycle/bmi_calc/src/app.ts|65 col 32 error| Supplied parameters do not match any signature of call target.

```

**Comment by vitiral** [comment]
Also, I thought it was weird that although the docs say that combine should be used like `xs.combine(weight$, height$)` I have to put them in an array `xs.combine([weight$, height$])`

**Comment by vitiral** [comment]
Also, is it recommended that I don't use typescript at this time?

**Comment by xtianjohns** [comment]
Hey @vitiral, if you try to compile either of the following examples, outside of any Cycle.js context, TypeScript should show you two of the four errors you are seeing.

```ts
import xs from 'xstream';
import { Stream } from 'xstream';

/**
 * "Supplied parameters do not match any signature of call target."
 * This is because Stream is being instantiated incorrectly.
 */
const badStream = xs.combine( xs.periodic( 100 ), xs.periodic( 400 ) )
  .map( ([ a, b ]) => new Stream( a, b ) ); // <= not exactly how we create Streams

/**
 * "Argument of type X is not assignable to parameter..."
 * This is because you're giving combine an array.
 */
const badCombine = xs.combine( [ xs.periodic( 100 ), xs.periodic( 400 ) ] );
```
I'm confident that the Typescript errors you are seeing are a result of these mismatched signatures. However, I think you'll iron it all out when making sure **that `model` is returning a stream that emits objects implementing `State`.**

Let's start here: are you giving the return value of `model` to a view function? If so, take a look at that function (`view`) and try to puzzle out what type it expects.

In the BMI Cycle.js example application, the model function's responsibility is to map changes to either height or weight (using `combine`) into an object that contains height, weight, and a calculated BMI. The data structure for those combined values (dubbed `State`) looks like this:

```ts
interface State {
  height: number;
  weight: number;
  bmi: number;
};

// in the Cycle.js example, where weight and height are numbers, and bmi => number

const State = {
  weight,
  height,
  bmi: bmi(weight, height)
}
```
Now let's take a look at the data structure for the combined values that you pasted in your initial comment:

```ts
new Stream( weight, height, calc_bmi( height, weight ) ) );
```
So now model might not correctly implement its signature, right? It'll provide a `Stream<Stream<something>>`, rather than a `Stream<State>`, where `State` is some structure that looks like my first example.

In the [Cycle.js example app](https://cycle.js.org/model-view-intent.html), it's implemented like so:
```ts
xs.combine( weight$, height$ )
  .map(( [ weight, height ] ) => {
    return { weight, height, bmi: bmi( weight, height ) };
  });
```
Notice that this stream will emit objects, not Streams. Start there, make a slight update to combine (give it each stream you'd like to combine, rather than an array), and you should be in better shape.

**Comment by vitiral** [comment]
Yes, you're right. I went back and started from the beginning and the errors went away. I'm pretty new to typescrypt, sorry!

**Comment by xtianjohns** [comment]
Glad it's working now! Don't be sorry at all - arguably this is exactly what makes TypeScript useful. Better that we all find these mistakes before we commit and deploy them.
