### ISSUE TITLE
Remove .from*(), have only .from()

### ISSUE THREAD

**Issue by nikoskalogridis** [staltz/xstream#149]
Is there a difference between the generalised version .from() function and the specialised .fromArray(), .fromObservable(), .fromPromise() that justifies the existence of the specialised versions on the API? I think that an API exposing fewer functions is always a better one. But then again that is only my opinion :-)

**Comment by whitecolor** [comment]
Just for api simplification, Rx for example does the same way.

**Comment by nikoskalogridis** [comment]
But if we are aiming at API simplification shouldn't we go for one function especially if one of the goals of xstream is to reduce the API surface of the library in order to avoid decision paralysis on picking an operator/factory.

**Comment by whitecolor** [comment]
No need to go crazy about reducing and simplifying api)

**Comment by staltz** [comment]
Yeah I would answer the same as @whitecolor. However, there's a good point here. We could remove those aliases. In xstream, like with Python, there should be just one obvious way of doing something.

**Comment by whitecolor** [comment]
@staltz This aliases `fromPromise, .fromArray, .fromObservable` could be removed, though they allow to be more explicit what it is wanted.

**Comment by artfuldev** [comment]
@staltz Having explicit methods could clarify intent better in some cases. Especially with JavaScript being dynamic.

**Comment by cortopy** [comment]
I bumped into this today but from another perspective as I actually prefer all the individual methods.

In my opinion `from` is confusing from a type-safe perspective. For me it's much better to think that `fromObservable` takes an observable and returns a stream, `fromArray` takes an array, etc. 

This still complies with the python approach, since "there is only one way of converting an array into a stream".

**Comment by staltz** [comment]
I agree too, and this issue has aged a bit.
