### ISSUE TITLE
Website missing ToC

### ISSUE THREAD

**Issue by staltz** [staltz/xstream#186]
Website https://staltz.com/xstream missing table of contents for operators

**Comment by xtianjohns** [comment]
Hey @staltz, I'm not sure how you're deploying staltz.com, but it looks like you've got two versions of the site up at two different domains.

ToC (and other content) is missing from staltz.com/xstream, but everything looks great locally and on staltz.github.io/xstream.

It looks like [staltz/staltz.com](https://github.com/staltz/staltz.com) has a folder for `xstream`, but it hasn't been updated in six months, which might explain the timing of this issue.

As an aside, I found this issue entangled with #132. Specifically, the behavior in #132 is missing for staltz.com/xstream (because it is "old"), but is present on staltz.github.io/xstream.

**Comment by staltz** [comment]
Hi @xtianjohns :)

I feel like deprecating the xstream site because it was mostly interesting at launch and with a nice theme, but now the overhead of maintaining it doesn't justify the benefits.

**Comment by xtianjohns** [comment]
Alrighty. Any alternatives, like maybe a Github wiki? Or you're thinking of just relying on the docs in source?

Tasks I can think of if you think deprecating is way to go:
- Update Repo URL on Github
- Update Readme
- Disable DNS for your domains
- Disable Github Pages for repo
- Delete gh-pages branch, or tag as "pages-archive" or something?
- Close this issue and #132.

If you can still be swayed, I think docs site is cool - helped me get up to speed on the library when starting out. But I hear you on maintenance.

**Comment by staltz** [comment]
Okay, I noticed actually everything is fine at http://staltz.github.io/xstream/
So let's just keep it. :)

Thanks @xtianjohns for the heads up. I'll try to replace links `staltz.com/xstream` to `staltz.github.io/xstream` whenever I find them.
