### ISSUE TITLE
Sync emission of circular streams

### ISSUE THREAD

**Issue by whitecolor** [staltz/xstream#198]
I just wonder if this case is working as expected and why:

```ts
const s1 = xs.create<number>()
const s2 = xs.create<number>()

s2.addListener({
  next: (val2) => {
    const val1 = val2 / 10 + 1
    console.warn('val1 send', val1)
    s1.shamefullySendNext(val1)
  }
})

s1.addListener({
  next: (val1) => {
    if (val1 < 5) {
      const val2 = val1 * 10
      console.warn('val2 send', val2)
      s2.shamefullySendNext(val2)
    }
  }
})


s1.addListener({
  next: (val1) => {
    console.warn('val1', val1)
  }
})

s2.addListener({
  next: (val2) => {
    console.warn('val2', val2)
  }
})

s1.shamefullySendNext(1)
```

Output is:
```
val2 send 10
val1 send 2
val2 send 20
val1 send 3
val2 send 30
val1 send 4
val2 send 40
val1 send 5
val1 5
val2 40
val1 4
val2 30
val1 3
val2 20
val1 2
val2 10
val1 1
```

**Comment by staltz** [comment]
I would say these are *correct semantics* but simply *weird semantics* because it's at the edges of xstream's purpose, not at the center.

Try putting these two listeners **first**, you'll get a different behavior:

```js
s1.addListener({
  next: (val1) => {
    console.warn('val1', val1)
  }
})

s2.addListener({
  next: (val2) => {
    console.warn('val2', val2)
  }
})
```

The reason is the recursive scheduler. The most intuitive scheduler for synchronous emissions is RxJS v4's trampoline scheduler. But synchronous emissions are not the best use case for reactive streams, and the trampoline scheduler costs a lot in performance, stack trace readability, etc.

(PS: I'm labeling this issue a discussion or a "question")
