### ISSUE TITLE
dropUntil doesn't complete output when other completes

### ISSUE THREAD

**Issue by whitecolor** [staltz/xstream#237]
Docs of `dropUntil` actually stand that:

> Starts emitting the input stream when another stream emits a next event. The output stream will complete if/when the other stream completes.

But actually, it is not the case, due [to this](https://github.com/staltz/xstream/blob/master/src/extra/dropUntil.ts#L17) `output` stream just start to emit when `other` stream completes.

[Test for this case ](https://github.com/staltz/xstream/blob/master/tests/extra/dropUntil.ts#L28) actually tests that `output` starts when `other` complets, though it is called `should complete the stream when another stream emits complete`.

So there's is something wrong with either the operator's code or its docs/tests.

**Comment by xtianjohns** [comment]
Hey @whitecolor, I think I understand what you are saying, but I believe the implementation actually should work fine. Specifically, doesn't [the "other internal listener"](https://github.com/staltz/xstream/blob/34ecda252d9773619c15c8f531b97b9caca2a989/src/extra/dropUntil.ts#L8-L10) catch the case of "starting" submissions on the source stream with the "other" stream emits?

When starting, we do monitor next emissions. You're correct that on complete we _also_ begin emitting items (`this.up()`), but we should also do that in the other internal listener. What do you think?

The test you link to is confusing a bit in its wording, but I'm not sure it actually tests what it should test. To verify, we should make the source stream infinite (concat with never or something), and note if the completion event on "other" actually ends "source". Since source ends anyway, we're not actually guaranteed to test our case properly. I _think_.

**Comment by whitecolor** [comment]
> You're correct that on complete we also begin emitting items (this.up()), but we should also do that in the other internal listener. What do you think?

To comply with this statement:

>  The output stream will complete if/when the other stream completes.

I think on completion of `other`, `output` should complete too, no?

**Comment by staltz** [comment]
Hey whitecolor and xtianjohns, thanks for investigating this.

I think we should follow the same behavior as RxJS skipUntil: https://github.com/ReactiveX/rxjs/blob/37d9ea9a8665d0c4b6593da4c237e037e98f66b5/spec/operators/skipUntil-spec.ts#L50-L60 unless we have a good reason to do something else.

**Comment by whitecolor** [comment]
So this actually should nor start emitting source (which is a current actual behavior) nor should complete it (which is a behaviour described in docs and test). 😃

**Comment by xtianjohns** [comment]
Hey @whitecolor, let me know if behavior in my PR makes sense to you - I'm happy to clarify here how it is changed.
