### ISSUE TITLE
Awful stack traces

### ISSUE THREAD

**Issue by janat08** [staltz/xstream#261]
This doesn't say anything at all about anything, while using onionify and trying to set up routing:
```
index.js:214 Uncaught TypeError: Cannot read property '_remove' of undefined
    at Combine._stop (index.js:214)
    at Stream._x (index.js:847)
    at Stream._e (index.js:812)
    at CombineListener._e (index.js:167)
    at MemoryStream.Stream._e (index.js:816)
    at MapOp._e (index.js:650)
    at MemoryStream.Stream._e (index.js:816)
    at _try (index.js:34)
    at MapOp._n (index.js:641)
    at MemoryStream.Stream._n (index.js:797)
```

**Comment by janat08** [comment]
I'm told this is duplicate of something, of what I don't know.

**Comment by janat08** [comment]
Anyhow expecting people to use typescript in lieu of catching errors to at least provide originating component is poor excuse.

**Comment by staltz** [comment]
Hi! The stack trace is not the best, but it could be much worse, for instance with RxJS v4 it was common to see a much longer stack trace riddled with details concerning the trampoline scheduler, and in comparison, the xstream stack trace is quite readable, in fact just by looking at it I can tell that the core problem was some argument passed to xs.combine was undefined while it was expected to be a stream (because only streams have _remove). So it's not correct to say "the stack trace doesn't say anything at all about anything", in fact it says a lot if you're willing to look into the source code of a (small) library. And it's also true that TypeScript would help and is low cost to add to a project. I'll close this issue because it's a complaint, not an actionable actual-versus-expected message.

**Comment by janat08** [comment]
Log in which parent function/component the failure occurred as the fact that it's combine with expectation of observable is fairly generic. Obviously it would be great if you could specifically point at a line of code, too.

**Comment by janat08** [comment]
I can make a new issue if this one won't be opened.
