### ISSUE TITLE
Errors not propagated through take(0)

### ISSUE THREAD

**Issue by Avaq** [staltz/xstream#267]
## Expected behavior

I expect the last statement in the following example to behave equally to the first and second.

```js
xs.throw(new Error).filter(_ => false).subscribe({error: console.log});
xs.throw(new Error).take(1).subscribe({error: console.log});
xs.throw(new Error).take(0).subscribe({error: console.log});
```

## Actual behavior

The error is silently ignored in the last statement, whereas it is logged in the former two.

## Context

I find myself in need sometimes to produce a Stream containing *only* the errors emitted on another Stream. My initial approach was to use `take(0)` on the source Stream, and `replaceErrors` on the result. Perhaps I'm simply looking in the wrong direction to achieve my goal, and I would appreciate some guidance if that's the case, but nonetheless, it seems odd to me that the argument to `take` should affect the error branch.

**Comment by staltz** [comment]
I understand this may feel unintuitive at first, and it also felt unintuitive to me, so I went and took a look at the source code. Then it became clear. `take(0)` means "don't subscribe to the source" because you won't take anything from it anyway. In other words, it's a race condition between the completion caused by the `take`, and the completion-or-error caused by the source. The way take works is that it only looks at number of `next` emissions in order to cause a completion, so with zero `next`s, it knows already to complete as soon as possible.

**Comment by Avaq** [comment]
Ahh. Of course. My misconception was that `take` keeps the stream in an uncompleted state after all events were "taken". So `take` is simply unsuited to express *__all__ errors on the source Stream*, because it has the capability to end the Stream.
