### ISSUE TITLE
Easy 'BehaviorSubject' equivalent?

### ISSUE THREAD

**Issue by ericvicenti** [staltz/xstream#274]
Hey @staltz, can't believe I'm only discovering this project in 2019, but it seems way easier to learn, compared to rxjs!

In rx, I can create a behavior subject pretty easily:

```js
const changingBool = new BehaviorSubject(true);
// folks may subscribe. To update:
changingBool.next(false);
```

With xstream, I struggle to do the same thing:

```js
let currentBoolValue = true;
let streamUpdater = null;
const changingBool = xs.createWithMemory({
  start: listener => {
    listener.next(currentBoolValue);
    streamUpdater = listener.next;
  },
  stop: () => {
    streamUpdater = null;
  }
});
function doUpdate(b) {
  currentBoolValue = b;
  streamUpdater && streamUpdater(b);
}
// folks may subscribe. To update:
doUpdate(false);
```

Granted, the xstream API is better because it prevents consumers of the stream from being able to call `.next` on the subject.

But it seems verbose for such a simple thing. Am I missing anything that would make this easier?

**Comment by staltz** [comment]
Hi @ericvicenti! Good to hear you're having a nice experience with xstream.

For BehaviorSubject purposes, I usually do

```js
const changingBool$ = xs.createWithMemory();
changingBool$.shamefullySendNext(true);
```

Note that `.shamefullySendNext` is by all means the same thing as RxJS's `.next`, the naming is just funny because it's a yellow warning that you're using the library in a way that is not as reactive as possible, much like React's `dangerouslySetInnerHTML` or `UNSAFE_componentWillUpdate`.

**Comment by ericvicenti** [comment]
Perfect, thanks!

I was wondering if there was an idiomatic solution. Might make sense to have something like the following:

```js
const [ changingBool$, setBool ] = xs.withMemory(); // naming is hard
// now people can consume changingBool$ without shame
setBool(true); // would do the "shameful" thing behind the scenes
```

**Comment by staltz** [comment]
I understand the wish. xstream is an opinionated take on reactive programming that tries to nudge you towards doing things in ways that are not natural (now), but will become natural once you get used to the paradigm. It's meant for beginners in reactive programming so it's kind of the "walled garden" approach instead of a free sandbox where you can do it however you wish.

If you want to build something like `withMemory`, I recommend doing that in the Callbag ecosystem of libraries (my other reactive programming project besides xstream), because the callbag spec is quite unopinionated and there's all kinds of utils built, see [the wiki](https://github.com/callbag/callbag/wiki). For instance, there's [behavior subject for callbags](https://github.com/zebulonj/callbag-behavior-subject) and a couple of react hooks for that: [[1]](https://github.com/Andarist/use-callbag) [[2]](https://github.com/Andarist/use-value-callbag/blob/master/src/index.js)
