### ISSUE TITLE
provide a `snapshot` operator

### ISSUE THREAD

**Issue by yelouafi** [staltz/xstream#39]
I was curious to know how xstream models the concept of State. Basically you can emulate the *stepper Behavior* concept from FRP (I mean behaviors varying discretely over time) by having 

1. a stream which remembers its last value: there is already `MemoryStream`

2. a way to create the stream with a start value (since a behavior have *always* a value): there is already the `remember` operator, it doesn't take a mandatory start value but I guess it can be combined with `startWith`.

3. the ability to `snapshot` that behavior at *any moment of interest*: of course by 'any moment' I don't mean any time/place in the code, but when some event happens in another stream.

In the classic FRP model, `snapshot` is considered a primitive, which means you can't create it by composing other primitives and operators.

Here is a simple example: suppose we have a simple todo list app and we have the following streams to represent its state

- `todoInput$` represents the state of the input text used to create new todos

- `todoList$` represents the state of the todo list

and suppose we have a stream `addTodo$` which models user intents to create new todos (e.g. a button click). 

Now on each `addTodo$` occurrence we need to 'sample' the `todoInput$` at this moment and use it to generate a new todo then add it to the todo list. With `snapshot` the code will be something like (I'm very new to xstream, so perhaps I missed something)

```js
// event stream
const newTodo$ = addTodo$.snapshot(todoInput$, (_, input) => ({title: input, done: false}))

// 'state stream' 
todoList$ =  newTodo$.startWith([]).fold((todoList, todo) => todoList.concat(todo)).remember()
```

Of course there are other ways to write the above example, like mapping `addTodo$` to `event.target.value` but there maybe cases when you can't provide the payload to the event directly and you have to construct it from the current state. You can also represent the whole state  as a single atom and then use merge/map then fold in a single function (a la Redux). But this would put more constraints on the users of the library (e.g. to be used outside of cyclejs scope). IMO, `snapshot` provides more means for composition inside an application.

**Comment by Widdershin** [comment]
Correct me if I'm wrong, but I think this has the same semantics as the `withLatestFrom` operator in RxJS.

So this code:
```js
// event stream
const newTodo$ = addTodo$.snapshot(todoInput$, (_, input) => ({title: input, done: false}))
```
is equivalent to 
```js
// event stream
const newTodo$ = todoInput$.map(input => addTodo$.mapTo({title: input, done: false})).flatten()
```

I asked this question regarding `withLatestFrom` in the gitter chat a while ago: [May 12, 2016 9:41 PM](https://gitter.im/staltz/xstream?at=57344fc3bce0284832d9dc51)

@staltz added this question to the [FAQ](https://github.com/staltz/xstream#faq).

I was initially confused that I had to write all of my `withlatestFrom`s the other way around but now I find it quite elegant, and I find working with `.map().flatten()` much more natural and composable.

For example, you could `filter` inside of the map as a means of sampling.

**Comment by yelouafi** [comment]
That's interesting! I was initially confused with `flatten` until I saw `flattenConcurrently` (Perhaps `switchToLatest` would be more appropriate). And effectively this method seems  more flexible.

One concern thou is with perf. implications b/c we're creating a stream on each keystoke. I dont know however if this case is optumized in the lib. Or if the overhead of creating new streams is not significative

**Comment by staltz** [comment]
Hi @yelouafi, thanks for opening the issue.

I'm aware of the concepts Behavior and Streams from classical FRP. xstream doesn't have these two separate types (as Bacon does), but that's just because I'm hoping to help people be familiar with event streams as a primitive, and then they can learn how to implement the Behavior *concept* with streams, through e.g. remember() and startWith(). It's basically: 2 concepts, 1 primitive. Versus 2 concepts, 2 primitives. This and other things in xstream's API (few operators e.g.) is made to help people focus on mastering one primitive.

> That's interesting! I was initially confused with flatten until I saw flattenConcurrently (Perhaps switchToLatest would be more appropriate). And effectively this method seems more flexible.

We did a lot of bikeshedding, Tylor and I, and we decided to settle on `flatten` with "switchToLatest" semantics for two reasons:
- It sets the expectation of what should be the default flattening strategy. switchToLatest is a better default because it solves the majority of the use cases (e.g. I haven't used flattenConcurrently not even once so far), and it is better for performance and memory.
- The name reads as "simple/naive flattening strategy", while flattenConcurrently is does much more.

> One concern thou is with perf. implications b/c we're creating a stream on each keystoke. I dont know however if this case is optumized in the lib. Or if the overhead of creating new streams is not significative

Shouldn't be a problem at all. I'm curious if you find a situation where it becomes a problem. We even optimized map+flatten with operator fusion, meaning whenever you do a flatten() after a map(), xstream actually replaces that with a `mapFlatten()` operator.

**Comment by staltz** [comment]
And if this discussions ends up describing a real issue in xstream, we'll reopen.

**Comment by yelouafi** [comment]
@staltz thanks for commenting. I also like the minimalist approach taken by this lib. 

For flatten I recognize the switchToLatest behavior is the most common (dynamic switching usually reflects control flow). But perhaps worth adding a note on the docs. People coming from other stream libs could assume the know what flatten does before reading the API docs for the function

**Comment by staltz** [comment]
Yes, I should add it to the FAQ or the `flatten()` docs or both.
