### ISSUE TITLE
dropRepeats should return a MemoryStream if the input was also a MemoryStream

### ISSUE THREAD

**Issue by Hypnosphi** [staltz/xstream#46]
Maybe some other extra methods should do that, too

**Comment by staltz** [comment]
Unfortunately not possible due to `compose` returning a `Stream` and we can't override `MemoryStream.compose` to always return a `MemoryStream` because it may be wrong in some cases.

For extra operators, we just need to cast to MemoryStream (in TypeScript) or add .remember (in TS or JS).

**Comment by PEZO19** [comment]
@staltz Isn't that possible nowadays with Typescript's Advanced Types? Would it be still useful? (Not knowing surely about the exact changes in the meaning of Stream/MemoryStream since.) I assume we could just build a simple wrapper Type which makes this distinction and might be even reused in multiple cases (different operators.) I can look into it if you think it's worthwhile.
