### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by mightyiam** [staltz/xstream#58]
I mistakenly used `xs.combine` as if it was Rx's `combineLatest`. So, I gave it a combining function.

It took me a while to debug. Not too long. A good error message would be very nice.

I'm sure that's only one example. Thus the general title.

**Comment by staltz** [comment]
I think we're not going to do this because it's development-time errors, so when running in production they would just take up space (kB) and processing.

If you use TypeScript, you get great development-time errors regarding API usage. Also, other libraries like RxJS and most.js don't do these type of errors.

**Comment by mightyiam** [comment]
Oh, wow. Isn't debugging streams hard enough? How about maintaining two packages, one of which has error messages? Perhaps automatically generated from TypeScript? Some kind of API wrappers that validate?

**Comment by mspoulsen** [comment]
I really miss error messages as well when developing. The "blank screen" is one of the hardest things about working with cycle.js. I have always wondered why there was never an error message to been seen, but now at least I understand the reasoning behind it. I am not one to say what is the best solution.

**Comment by mightyiam** [comment]
@mspoulsen, @staltz is referring to xstream, in this regard. For Cycle.js, I've understood that helpful errors would be very welcomed additions.

**Comment by staltz** [comment]
TypeScript fixes these issues. Give it a try

> How about maintaining two packages, one of which has error messages?

How about a pull request?

**Comment by Widdershin** [comment]
>  I think we're not going to do this because it's development-time errors, so when running in production they would just take up space (kB) and processing.

> If you use TypeScript, you get great development-time errors regarding API usage. Also, other libraries like RxJS and most.js don't do these type of errors.

Most users don't use TypeScript, and RxJS can be very confusing in part because of terrible errors. One of the biggest complaints about React is that the errors aren't helpful.

How much of a performance loss would it be? Because I think that helpful errors are worth a small (>1%) loss in performance.

**Comment by staltz** [comment]
I don't want people to think I'm angry at this suggestion or not trying to help, but this suggestion won't happen, I'm not going to build it and it's not going to help people.

Building these type of "API misuse errors" is essentially building a weak type checking system. Please recognize that if we would try to **write as perfect errors as possible**, we would basically be building a crappy version of TypeScript. Worse, it'd run in runtime, not in compile time. Worse, you wouldn't have that feedback in real time in an IDE.

I'm looking for the ideal developer experience, and the **best possible** error feedback of API misuse is something like a compile-time type checker or linter. And you can get awesome DX **today** with TypeScript.

> Most users don't use TypeScript

They should **if** they want these helpful API misuse warning/errors. Please notice that **by using JavaScript**, you are acknowledging that you are taking these risks. And this happens ubiquitously with all sorts of libraries and native APIs. If you want helpful API misuse errors, the ideal solution is not to bake in those errors in runtime, the ideal solution is a typed language.

Just give it a try, TypeScript is so easy to adopt. This issue won't happen, and it's not because I'm ignorant to people's problems, it's because it would never be good enough, and the effort would be large.

**Comment by Widdershin** [comment]
I don't mean to argue that we should attempt to cover every single possible API misuse with a runtime error, but can't we consider each on a case by case basis? Why can't we weight up the performance/size cost against the potential trouble we might save developers (as we have already done for `addListener`)?

I think it's especially important to consider that the people who will be most impacted by these errors are beginners or people just adopting xstream. There is a world of difference between spending hours battling with a cryptic error message vs a plain English description of what went wrong and how to fix it.

I think there is a certain amount of pragmatism called for here. We should certainly not add runtime errors for every misuse, but if we can save people (especially beginners) needless frustration, I think that can be very worthwhile.

**Comment by mightyiam** [comment]
I see the point, of course.
How much penalty do you guys think that something like https://www.npmjs.com/package/runtime-type-checks incur?
