### ISSUE TITLE
mapTo - only constants?

### ISSUE THREAD

**Issue by mspoulsen** [staltz/xstream#77]
I was fooled by mapTo today:

```javascript
    .select('.random')
    .events('click')
    .mapTo({ type : 'RANDOM', payload : Math.random() });
```
Here I got same result every time. I expected a new number each time. I thought mapTo could be used anytime we didn't care about the input, but instead the value is cached it seems.

Is this by design?

**Comment by staltz** [comment]
It's not only by design, it's impossible to "fix" this, because JavaScript has eager evaluation. `{type: 'RANDOM', payload: Math.random()}` is evaluated **and then** it's given to `mapTo` as a constant. If you want a new evaluation of `Math.random()`, there's no other way than using `map(() => {type: 'RANDOM', payload: Math.random()})` because then each time that function is called it evaluates `Math.random()` again. It's not about caching.

**Comment by mspoulsen** [comment]
I see! Of course, now that I actually think about it :smile: Thanks!

**Comment by staltz** [comment]
Another way of seeing it is that `mapTo(c)` takes a **constant**. So you can't expect it to be different every time. :)
