### ISSUE TITLE
Single letter variable names in source

### ISSUE THREAD

**Issue by Widdershin** [staltz/xstream#88]
I'm curious, why does the xstream source code use single letter variable names?

I think that it makes the xstream source much harder to read than it needs to be. It also makes for confusing errors (`this.s is not a function`).

I understand that it is a design priority of `xstream` to have a very small filesize. However, surely `uglify` also minifies variable names, or we could get a tool to do so?

**Comment by staltz** [comment]
It's not a design goal in xstream to emit very user friendly error messages because we rely on TypeScript for that end.

We need to minify a lot of stuff by hand because uglify can't do everything. For instance it wouldn't uglify property names of objects, since those may be accessed by string in runtime code. It minimizes just simple variable names. If you find a way to uglify those through `uglify`, I think that would be a good PR.

**Comment by Widdershin** [comment]
Okay, that makes sense.

I'm curious if you think the cost to readability is worth the saved bytes. It makes it harder for any given dev to understand and learn from the xstream source.

**Comment by staltz** [comment]
However, where applicable, I've written a comment that explains the naming of a variable, like here: https://github.com/staltz/xstream/blob/master/src/core.ts#L237

We could do that more.

**Comment by staltz** [comment]
And in fact, `this.s` also had a comment: https://github.com/staltz/xstream/blob/master/src/core.ts#L366 ;)

**Comment by staltz** [comment]
I might be biased, but I also think xstream's codebase is more understandable than RxJS v4 and Bacon.js, specially because with xstream you can check the type of any variable.

RxJS v5 codebase is probably the most understandable.

**Comment by Widdershin** [comment]
I can't speak for Bacon, but I agree that's it better than RxJS v4.

Thanks for the answers. I'll have a think about tooling, maybe we could do that PR for uglify.
